MONGODB_HOST: mongodb-{{  env }}.expense.icu
REDIS_HOST: redis-{{  env }}.expense.icu
CATALOGUE_HOST: catalogue-{{  env }}.expense.icu
CART_HOST: cart-{{  env }}.expense.icu
USER_HOST: user-{{  env }}.expense.icu
RABBITMQ_HOST: rabbitmq-{{  env }}.expense.icu
MYSQL_HOST: mysql-{{  env }}.expense.icu
SHIPPING_HOST: shipping-{{  env }}.expense.icu
PAYMENT_HOST: payment-{{  env }}.expense.icu