MONGODB_HOST: mongodb.expense.icu
REDIS_HOST: redis.expense.icu
CATALOGUE_HOST: catalogue.expense.icu
CART_HOST: cart.expense.icu
USER_HOST: user.expense.icu
RABBITMQ_HOST: rabbitmq.expense.icu
MYSQL_HOST: mysql.expense.icu
SHIPPING_HOST: shipping.expense.icu
PAYMENT_HOST: payment.expense.icu